### ISSUE TITLE
Create a list of Bioboxes

### ISSUE THREAD

**Issue by pbelmann** [tlaufkoetter/biobox-gui#1]
Bioboxes GUI must list interfaces and the implementing bioboxes. 
[This](https://github.com/bioboxes/data/blob/master/images.yml) yaml represents current biobox implementations.

This might change with PR bioboxes/data#2
So it is not clear which one the future image list will be. @tlaufkoetter It's up to you which one you choose for the GUI.

**Comment by tlaufkoetter** [comment]
I decided to use your second suggestion, because in this version the keys are just keys and not data.
