### ISSUE TITLE
Human and Machine readable Bioboxes specification and description

### ISSUE THREAD

**Issue by pbelmann** [tlaufkoetter/biobox-gui#6]
At the moment there is just a human readable bioboxes specification ([assembler interface](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd)). 
It would help to define a specification which
1. is human readable and would allow a user to understand the specification
2. is machine readable and could for example help to generate an input form (see #5 ) in the bioboxes gui

Our initial ideas are:
- Use JSON-LD für linking data
- Define templates for possible new specification
- Use XMLSchema as an ideal
- Create a wizard for creating specifications (nice to have)

**Comment by jkrue** [comment]
We need a somehow EDAM Meta Schema.
- JasonSchema 
- JasonLD (Link to EDAM types)

**Comment by pbelmann** [comment]
If you decide to use json-schema for validating jsons, I recommend this library https://github.com/Julian/jsonschema
